apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app-deployment
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        # ports:
        # - containerPort: 80
        - name: mongodb
          image: mongo:latest
          volumeMounts: 
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: host-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: service-mogodb
spec:
  #type: LoadBalancer
  selector:
    app: mongo-app
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
      
      