apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        # ports:
        # - containerPort: 80
      - name: node-app
        image: salmanbintariq007/db-demo:v4 
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_PORT      
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeapp
spec:
  #type: LoadBalancer
  selector:
    app: node-app
  type: LoadBalancer  
  ports:
    - name: http
      port: 8080
      targetPort: 3000
    
      